ersion: '3.8'

services:
  beammp:
    build: .
    container_name: beammp-server
    ports:
      - "30814:30814/tcp"
      - "30814:30814/udp"
    volumes:
      - ./ServerConfig.toml:/server/ServerConfig.toml
      - ./mods/Client:/server/Resources/Client

    restart: unless-stopped
    deploy: