FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    liblua5.3 \
    unzip libcurl4-openssl-dev screen iproute2 && \
    apt-get clean

WORKDIR /server

COPY server-bin/BeamMP-Server /server/BeamMP-Server
COPY ServerConfig.toml /server/ServerConfig.toml

RUN chmod +x /server/BeamMP-Server

CMD ["./BeamMP-Server"]

#changed some shit